name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Build Windows .exe
        run: GOOS=windows GOARCH=amd64 go build -o panoptorip.exe .

      - name: Build macOS binary
        run: GOOS=darwin GOARCH=amd64 go build -o panoptorip-mac .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            panoptorip.exe
            panoptorip-mac
